
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qualibug-v11
spec:
  replicas: 3
  selector:
    matchLabels:
      app: qualibug
  template:
    metadata:
      labels:
        app: qualibug
    spec:
      containers:
      - name: api
        image: qualibug:v11
        ports:
        - containerPort: 8000
