
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qualibug
spec:
  replicas: 3
  selector:
    matchLabels:
      app: qualibug
  template:
    metadata:
      labels:
        app: qualibug
    spec:
      containers:
      - name: api
        image: qualibug:latest
        ports:
        - containerPort: 8088
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "2000m"
            memory: "2Gi"
