import type {
  EnvironmentDiagnosticEdge,
  EnvironmentDiagnosticGate,
  EnvironmentDiagnosticGraph,
  EnvironmentDiagnosticNode,
} from "./model";

function gates(): readonly EnvironmentDiagnosticGate[] {
  return [
    {
      gateId: "runtime_start_allowed",
      label: "Runtime Start",
      status: "blocked",
      allowed: false,
      summary: "正式 runtime 启动",
      reason: "仍存在环境阻断项，暂不允许直接进入正式 runtime。",
      remediationAction: "先关闭环境阻断项，再重新执行预检。",
    },
    {
      gateId: "readonly_probe_allowed",
      label: "Readonly Probe",
      status: "warning",
      allowed: true,
      summary: "只读探针",
      reason: "基础连通性可验证，但建议保持只读或沙箱模式。",
      remediationAction: "优先在只读模式验证认证、链路与 API smoke。",
    },
    {
      gateId: "write_probe_allowed",
      label: "Write Probe",
      status: "blocked",
      allowed: false,
      summary: "写入型探针",
      reason: "当前环境未给出足够安全边界，不应直接执行写入动作。",
      remediationAction: "补充测试租户、回滚策略与安全窗口说明。",
    },
    {
      gateId: "p0p1_validation_allowed",
      label: "P0/P1 Validation",
      status: "warning",
      allowed: true,
      summary: "高优先级问题验证",
      reason: "可在受限模式下验证关键问题，但不应放量执行。",
      remediationAction: "先锁定阻断项，再扩大验证范围。",
    },
  ];
}

function nodes(): readonly EnvironmentDiagnosticNode[] {
  return [
    {
      nodeId: "entrypoint",
      label: "客户入口",
      kind: "entrypoint",
      stageId: "access",
      status: "warning",
      headline: "目标环境已识别",
      detail: "已定位项目入口，但仍需客户确认边界与访问方式。",
      businessExplanation: "入口清晰后，后续探针才能稳定命中真实业务路径。",
      nextAction: "确认预生产 / 测试环境地址及访问窗口。",
      gateIds: ["readonly_probe_allowed"],
      blockerIds: [],
    },
    {
      nodeId: "url",
      label: "URL / 路由",
      kind: "network",
      stageId: "access",
      status: "passed",
      headline: "地址格式通过",
      detail: "目标 URL 可解析为后续预检请求。",
      businessExplanation: "地址结构正确，才能继续验证 DNS / HTTP / 认证链。",
      nextAction: "保持当前目标地址。",
      gateIds: ["readonly_probe_allowed"],
      blockerIds: [],
    },
    {
      nodeId: "dns",
      label: "DNS / Host",
      kind: "network",
      stageId: "network",
      status: "warning",
      headline: "网络连通性待确认",
      detail: "存在白名单或代理说明缺失的风险。",
      businessExplanation: "DNS 或网络出口不稳定会直接阻断后续 API smoke。",
      nextAction: "补充 VPN / 代理 / 白名单策略。",
      gateIds: ["readonly_probe_allowed"],
      blockerIds: ["blocker-network"],
    },
    {
      nodeId: "http",
      label: "HTTP / HTTPS",
      kind: "security",
      stageId: "network",
      status: "warning",
      headline: "基础可达但需确认 TLS",
      detail: "HTTP 层可访问，但证书或网关策略仍需客户确认。",
      businessExplanation: "如果 TLS 或网关策略未对齐，正式 runtime 会不稳定。",
      nextAction: "确认证书、网关和预生产访问策略。",
      gateIds: ["readonly_probe_allowed", "runtime_start_allowed"],
      blockerIds: ["blocker-network"],
    },
    {
      nodeId: "auth",
      label: "认证与会话",
      kind: "auth",
      stageId: "identity",
      status: "warning",
      headline: "登录态未完全闭环",
      detail: "认证上下文可识别，但仍有测试账号或 MFA 绕过问题。",
      businessExplanation: "认证未闭环时，业务链路 smoke 只能做有限验证。",
      nextAction: "提供测试账号、SSO 绕过策略或会话说明。",
      gateIds: ["readonly_probe_allowed", "p0p1_validation_allowed"],
      blockerIds: ["blocker-auth"],
    },
    {
      nodeId: "account-matrix",
      label: "账号矩阵",
      kind: "account",
      stageId: "identity",
      status: "blocked",
      headline: "缺少关键测试账号",
      detail: "管理员 / 运营 / 财务等关键角色尚未全部到位。",
      businessExplanation: "没有角色矩阵就无法覆盖高价值业务路径。",
      nextAction: "补齐至少一组可用测试角色与权限范围。",
      gateIds: ["write_probe_allowed", "p0p1_validation_allowed"],
      blockerIds: ["blocker-auth"],
    },
    {
      nodeId: "api-smoke",
      label: "API Smoke",
      kind: "api",
      stageId: "probe",
      status: "warning",
      headline: "最小链路通过率有限",
      detail: "部分接口可以验证，关键业务接口仍存在权限或租户绑定问题。",
      businessExplanation: "API smoke 用来确认不是业务 Bug，而是环境或权限阻断。",
      nextAction: "修复失败接口的权限、路径或租户绑定。",
      gateIds: ["readonly_probe_allowed", "p0p1_validation_allowed"],
      blockerIds: ["blocker-api"],
    },
    {
      nodeId: "test-data",
      label: "测试数据",
      kind: "data",
      stageId: "probe",
      status: "warning",
      headline: "业务样例不足",
      detail: "缺少能够覆盖支付、退款等关键链路的演示数据。",
      businessExplanation: "没有可回放样例，风险验证与复现质量会明显下降。",
      nextAction: "提供最小可复现样例或测试租户数据。",
      gateIds: ["p0p1_validation_allowed", "write_probe_allowed"],
      blockerIds: ["blocker-data"],
    },
    {
      nodeId: "snapshot",
      label: "快照与脱敏",
      kind: "snapshot",
      stageId: "safety",
      status: "passed",
      headline: "默认脱敏开启",
      detail: "不会在界面中展示原始 token、cookie 或 secret。",
      businessExplanation: "保证环境诊断输出可用于客户沟通而不泄露敏感信息。",
      nextAction: "保持当前脱敏策略。",
      gateIds: ["readonly_probe_allowed", "p0p1_validation_allowed"],
      blockerIds: [],
    },
    {
      nodeId: "cleanup",
      label: "清理与回滚",
      kind: "cleanup",
      stageId: "safety",
      status: "warning",
      headline: "安全模式受限",
      detail: "当前建议保持只读 / 分层模式，不宜直接做写入回放。",
      businessExplanation: "没有清理与回滚策略时，写入探针风险过高。",
      nextAction: "明确回滚策略、数据隔离和安全时间窗。",
      gateIds: ["write_probe_allowed"],
      blockerIds: ["blocker-data"],
    },
    {
      nodeId: "runtime",
      label: "Runtime Allowed",
      kind: "runtime",
      stageId: "runtime",
      status: "blocked",
      headline: "正式 runtime 暂不可开启",
      detail: "当前更适合继续做环境补料和受限验证。",
      businessExplanation: "只有前置门禁闭环，runtime 结果才可信且可交付。",
      nextAction: "关闭阻断项后重新运行环境预检。",
      gateIds: ["runtime_start_allowed", "readonly_probe_allowed", "write_probe_allowed", "p0p1_validation_allowed"],
      blockerIds: ["blocker-network", "blocker-auth", "blocker-api", "blocker-data"],
    },
  ];
}

function edges(): readonly EnvironmentDiagnosticEdge[] {
  return [
    { edgeId: "entrypoint-url", sourceNodeId: "entrypoint", targetNodeId: "url", label: "识别入口", status: "passed" },
    { edgeId: "url-dns", sourceNodeId: "url", targetNodeId: "dns", label: "解析 Host", status: "warning" },
    { edgeId: "dns-http", sourceNodeId: "dns", targetNodeId: "http", label: "确认可达", status: "warning" },
    { edgeId: "http-auth", sourceNodeId: "http", targetNodeId: "auth", label: "进入认证", status: "warning" },
    { edgeId: "auth-account", sourceNodeId: "auth", targetNodeId: "account-matrix", label: "装配角色", status: "blocked" },
    { edgeId: "account-api", sourceNodeId: "account-matrix", targetNodeId: "api-smoke", label: "执行 smoke", status: "warning" },
    { edgeId: "api-data", sourceNodeId: "api-smoke", targetNodeId: "test-data", label: "进入业务样例", status: "warning" },
    { edgeId: "data-snapshot", sourceNodeId: "test-data", targetNodeId: "snapshot", label: "生成证据", status: "warning" },
    { edgeId: "snapshot-cleanup", sourceNodeId: "snapshot", targetNodeId: "cleanup", label: "保证安全", status: "warning" },
    { edgeId: "cleanup-runtime", sourceNodeId: "cleanup", targetNodeId: "runtime", label: "放行 runtime", status: "blocked" },
  ];
}

export function buildEnvironmentDiagnosticsMockGraph(projectId: string): EnvironmentDiagnosticGraph {
  return {
    projectId,
    source: "mock",
    summary: {
      status: "warning",
      score: 68,
      verdict: "可进入受限测试",
      reason: "基础连通性已具备，但账号矩阵、API 权限和测试数据仍需客户补料。",
      safeExecutionMode: "read_only",
      checkedAt: "2026-06-29T09:11:00.000Z",
      redactionStatus: "safe",
    },
    gates: gates(),
    nodes: nodes(),
    edges: edges(),
    blockers: [
      {
        blockerId: "blocker-network",
        title: "网络与网关策略待确认",
        summary: "DNS / HTTPS 尚未完全稳定，可能受白名单、代理或网关策略影响。",
        status: "warning",
        reason: "基础地址可达，但正式 runtime 前仍需确认访问边界。",
        remediationAction: "补充 VPN / 代理 / 白名单与证书策略。",
        nodeIds: ["dns", "http", "runtime"],
        gateIds: ["runtime_start_allowed", "readonly_probe_allowed"],
      },
      {
        blockerId: "blocker-auth",
        title: "测试账号与认证闭环不足",
        summary: "关键角色账号和 SSO / MFA 测试策略尚未准备完整。",
        status: "blocked",
        reason: "缺少可用账号矩阵会直接阻断关键链路验证。",
        remediationAction: "补齐测试角色、权限范围和认证绕过说明。",
        nodeIds: ["auth", "account-matrix", "runtime"],
        gateIds: ["write_probe_allowed", "p0p1_validation_allowed", "runtime_start_allowed"],
      },
      {
        blockerId: "blocker-api",
        title: "关键 API smoke 未通过",
        summary: "部分最小业务接口仍存在权限、路径或租户绑定问题。",
        status: "warning",
        reason: "需要先区分环境问题与业务 Bug，避免误判。",
        remediationAction: "修复失败接口的权限、路径或租户绑定。",
        nodeIds: ["api-smoke", "runtime"],
        gateIds: ["readonly_probe_allowed", "p0p1_validation_allowed"],
      },
      {
        blockerId: "blocker-data",
        title: "测试数据与回滚策略不足",
        summary: "缺少稳定的测试样例与写入回滚方案。",
        status: "warning",
        reason: "没有安全边界时，不应直接执行写入型探针。",
        remediationAction: "提供测试数据、隔离租户和回滚说明。",
        nodeIds: ["test-data", "cleanup", "runtime"],
        gateIds: ["write_probe_allowed", "runtime_start_allowed"],
      },
    ],
    requiredCustomerInputs: [
      {
        inputId: "input-role-accounts",
        title: "测试账号矩阵",
        priority: "high",
        status: "pending",
        whyNeeded: "用于覆盖支付、退款、运营等关键业务角色。",
        suggestedInput: "至少提供管理员、运营、财务各 1 组测试账号。",
        affectedFlows: ["下单支付主链路", "退款对账链路"],
      },
      {
        inputId: "input-network-whitelist",
        title: "网络白名单说明",
        priority: "medium",
        status: "pending",
        whyNeeded: "用于确认测试机出口、VPN 或代理访问策略。",
        suggestedInput: "提供可访问范围、代理地址或 VPN 指引。",
        affectedFlows: ["所有环境预检"],
      },
      {
        inputId: "input-test-data",
        title: "最小业务样例",
        priority: "medium",
        status: "pending",
        whyNeeded: "用于完成 API smoke 和后续证据回放。",
        suggestedInput: "提供 1 组支付 / 退款最小可复现样例。",
        affectedFlows: ["下单支付主链路", "退款对账链路"],
      },
    ],
    suggestedActions: [
      "补齐测试账号矩阵并确认 SSO / MFA 测试绕过方式。",
      "确认 DNS / HTTPS / 网关策略，先打通最小可达链路。",
      "修复失败 API 的权限或租户绑定后重新执行预检。",
      "在只读模式下继续推进 API smoke，再决定是否开启写入探针。",
    ],
  };
}
