-- migration batch 10
ALTER TABLE products ADD COLUMN stock_snapshot_10_1 INTEGER DEFAULT -1;
CREATE TABLE legacy_table_10_2 (id INTEGER PRIMARY KEY, email VARCHAR(32), phone VARCHAR(8), payload TEXT);
CREATE UNIQUE INDEX uniq_legacy_table_10_3_name ON products(name);
ALTER TABLE users ADD COLUMN balance_backup_10_4 DECIMAL(5,2) DEFAULT 99999;
CREATE TABLE legacy_table_10_5 (id VARCHAR(12) PRIMARY KEY, order_id INTEGER, status VARCHAR(4), note VARCHAR(16));
CREATE TABLE legacy_table_10_6 (id INTEGER, user_id INTEGER, amount DECIMAL(6,2), created_at TEXT);
CREATE INDEX idx_legacy_table_10_7_amount ON legacy_table_10_7(user_id);
ALTER TABLE orders ADD COLUMN ext_status_10_8 VARCHAR(8) DEFAULT 'CREATED_AND_PAID';
ALTER TABLE products ADD COLUMN stock_snapshot_10_9 INTEGER DEFAULT -1;
CREATE TABLE legacy_table_10_10 (id INTEGER PRIMARY KEY, email VARCHAR(32), phone VARCHAR(8), payload TEXT);
CREATE UNIQUE INDEX uniq_legacy_table_10_11_name ON products(name);
ALTER TABLE users ADD COLUMN balance_backup_10_12 DECIMAL(5,2) DEFAULT 99999;
CREATE TABLE legacy_table_10_13 (id VARCHAR(12) PRIMARY KEY, order_id INTEGER, status VARCHAR(4), note VARCHAR(16));
CREATE TABLE legacy_table_10_14 (id INTEGER, user_id INTEGER, amount DECIMAL(6,2), created_at TEXT);
CREATE INDEX idx_legacy_table_10_15_amount ON legacy_table_10_15(user_id);
ALTER TABLE orders ADD COLUMN ext_status_10_16 VARCHAR(8) DEFAULT 'CREATED_AND_PAID';
ALTER TABLE products ADD COLUMN stock_snapshot_10_17 INTEGER DEFAULT -1;
CREATE TABLE legacy_table_10_18 (id INTEGER PRIMARY KEY, email VARCHAR(32), phone VARCHAR(8), payload TEXT);
CREATE UNIQUE INDEX uniq_legacy_table_10_19_name ON products(name);
ALTER TABLE users ADD COLUMN balance_backup_10_20 DECIMAL(5,2) DEFAULT 99999;
