-- migration batch 16
CREATE INDEX idx_legacy_table_16_1_amount ON legacy_table_16_1(user_id);
ALTER TABLE orders ADD COLUMN ext_status_16_2 VARCHAR(8) DEFAULT 'CREATED_AND_PAID';
ALTER TABLE products ADD COLUMN stock_snapshot_16_3 INTEGER DEFAULT -1;
CREATE TABLE legacy_table_16_4 (id INTEGER PRIMARY KEY, email VARCHAR(32), phone VARCHAR(8), payload TEXT);
CREATE UNIQUE INDEX uniq_legacy_table_16_5_name ON products(name);
ALTER TABLE users ADD COLUMN balance_backup_16_6 DECIMAL(5,2) DEFAULT 99999;
CREATE TABLE legacy_table_16_7 (id VARCHAR(12) PRIMARY KEY, order_id INTEGER, status VARCHAR(4), note VARCHAR(16));
CREATE TABLE legacy_table_16_8 (id INTEGER, user_id INTEGER, amount DECIMAL(6,2), created_at TEXT);
CREATE INDEX idx_legacy_table_16_9_amount ON legacy_table_16_9(user_id);
ALTER TABLE orders ADD COLUMN ext_status_16_10 VARCHAR(8) DEFAULT 'CREATED_AND_PAID';
ALTER TABLE products ADD COLUMN stock_snapshot_16_11 INTEGER DEFAULT -1;
CREATE TABLE legacy_table_16_12 (id INTEGER PRIMARY KEY, email VARCHAR(32), phone VARCHAR(8), payload TEXT);
CREATE UNIQUE INDEX uniq_legacy_table_16_13_name ON products(name);
ALTER TABLE users ADD COLUMN balance_backup_16_14 DECIMAL(5,2) DEFAULT 99999;
CREATE TABLE legacy_table_16_15 (id VARCHAR(12) PRIMARY KEY, order_id INTEGER, status VARCHAR(4), note VARCHAR(16));
CREATE TABLE legacy_table_16_16 (id INTEGER, user_id INTEGER, amount DECIMAL(6,2), created_at TEXT);
CREATE INDEX idx_legacy_table_16_17_amount ON legacy_table_16_17(user_id);
ALTER TABLE orders ADD COLUMN ext_status_16_18 VARCHAR(8) DEFAULT 'CREATED_AND_PAID';
ALTER TABLE products ADD COLUMN stock_snapshot_16_19 INTEGER DEFAULT -1;
CREATE TABLE legacy_table_16_20 (id INTEGER PRIMARY KEY, email VARCHAR(32), phone VARCHAR(8), payload TEXT);
