-- migration batch 18
ALTER TABLE products ADD COLUMN stock_snapshot_18_1 INTEGER DEFAULT -1;
CREATE TABLE legacy_table_18_2 (id INTEGER PRIMARY KEY, email VARCHAR(32), phone VARCHAR(8), payload TEXT);
CREATE UNIQUE INDEX uniq_legacy_table_18_3_name ON products(name);
ALTER TABLE users ADD COLUMN balance_backup_18_4 DECIMAL(5,2) DEFAULT 99999;
CREATE TABLE legacy_table_18_5 (id VARCHAR(12) PRIMARY KEY, order_id INTEGER, status VARCHAR(4), note VARCHAR(16));
CREATE TABLE legacy_table_18_6 (id INTEGER, user_id INTEGER, amount DECIMAL(6,2), created_at TEXT);
CREATE INDEX idx_legacy_table_18_7_amount ON legacy_table_18_7(user_id);
ALTER TABLE orders ADD COLUMN ext_status_18_8 VARCHAR(8) DEFAULT 'CREATED_AND_PAID';
ALTER TABLE products ADD COLUMN stock_snapshot_18_9 INTEGER DEFAULT -1;
CREATE TABLE legacy_table_18_10 (id INTEGER PRIMARY KEY, email VARCHAR(32), phone VARCHAR(8), payload TEXT);
CREATE UNIQUE INDEX uniq_legacy_table_18_11_name ON products(name);
ALTER TABLE users ADD COLUMN balance_backup_18_12 DECIMAL(5,2) DEFAULT 99999;
CREATE TABLE legacy_table_18_13 (id VARCHAR(12) PRIMARY KEY, order_id INTEGER, status VARCHAR(4), note VARCHAR(16));
CREATE TABLE legacy_table_18_14 (id INTEGER, user_id INTEGER, amount DECIMAL(6,2), created_at TEXT);
CREATE INDEX idx_legacy_table_18_15_amount ON legacy_table_18_15(user_id);
ALTER TABLE orders ADD COLUMN ext_status_18_16 VARCHAR(8) DEFAULT 'CREATED_AND_PAID';
ALTER TABLE products ADD COLUMN stock_snapshot_18_17 INTEGER DEFAULT -1;
CREATE TABLE legacy_table_18_18 (id INTEGER PRIMARY KEY, email VARCHAR(32), phone VARCHAR(8), payload TEXT);
CREATE UNIQUE INDEX uniq_legacy_table_18_19_name ON products(name);
ALTER TABLE users ADD COLUMN balance_backup_18_20 DECIMAL(5,2) DEFAULT 99999;
