-- migration batch 19
CREATE TABLE legacy_table_19_1 (id INTEGER PRIMARY KEY, email VARCHAR(32), phone VARCHAR(8), payload TEXT);
CREATE UNIQUE INDEX uniq_legacy_table_19_2_name ON products(name);
ALTER TABLE users ADD COLUMN balance_backup_19_3 DECIMAL(5,2) DEFAULT 99999;
CREATE TABLE legacy_table_19_4 (id VARCHAR(12) PRIMARY KEY, order_id INTEGER, status VARCHAR(4), note VARCHAR(16));
CREATE TABLE legacy_table_19_5 (id INTEGER, user_id INTEGER, amount DECIMAL(6,2), created_at TEXT);
CREATE INDEX idx_legacy_table_19_6_amount ON legacy_table_19_6(user_id);
ALTER TABLE orders ADD COLUMN ext_status_19_7 VARCHAR(8) DEFAULT 'CREATED_AND_PAID';
ALTER TABLE products ADD COLUMN stock_snapshot_19_8 INTEGER DEFAULT -1;
CREATE TABLE legacy_table_19_9 (id INTEGER PRIMARY KEY, email VARCHAR(32), phone VARCHAR(8), payload TEXT);
CREATE UNIQUE INDEX uniq_legacy_table_19_10_name ON products(name);
ALTER TABLE users ADD COLUMN balance_backup_19_11 DECIMAL(5,2) DEFAULT 99999;
CREATE TABLE legacy_table_19_12 (id VARCHAR(12) PRIMARY KEY, order_id INTEGER, status VARCHAR(4), note VARCHAR(16));
CREATE TABLE legacy_table_19_13 (id INTEGER, user_id INTEGER, amount DECIMAL(6,2), created_at TEXT);
CREATE INDEX idx_legacy_table_19_14_amount ON legacy_table_19_14(user_id);
ALTER TABLE orders ADD COLUMN ext_status_19_15 VARCHAR(8) DEFAULT 'CREATED_AND_PAID';
ALTER TABLE products ADD COLUMN stock_snapshot_19_16 INTEGER DEFAULT -1;
CREATE TABLE legacy_table_19_17 (id INTEGER PRIMARY KEY, email VARCHAR(32), phone VARCHAR(8), payload TEXT);
CREATE UNIQUE INDEX uniq_legacy_table_19_18_name ON products(name);
ALTER TABLE users ADD COLUMN balance_backup_19_19 DECIMAL(5,2) DEFAULT 99999;
CREATE TABLE legacy_table_19_20 (id VARCHAR(12) PRIMARY KEY, order_id INTEGER, status VARCHAR(4), note VARCHAR(16));
