// Auto-generated by QualiBug Phase104B API contract exporter.
// Safe for frontend integration. Do not log request bodies containing credentials.

export type ApiEnvelope<T = unknown> = {
  success: boolean;
  data: T | null;
  error: null | { code: string; message: string; status?: number; details?: Record<string, unknown> };
  meta?: Record<string, unknown>;
};

export class QualiBugCommandCenterClient {
  constructor(private readonly baseUrl: string = 'http://127.0.0.1:8790') {}

  private async request<T>(method: string, path: string, body?: unknown): Promise<T> {
    const response = await fetch(`${this.baseUrl}${path}`, {
      method,
      headers: { 'Content-Type': 'application/json' },
      body: body === undefined ? undefined : JSON.stringify(body),
    });
    const envelope = (await response.json()) as ApiEnvelope<T>;
    if (!envelope.success) {
      throw new Error(envelope.error?.message || `QualiBug API error: ${response.status}`);
    }
    return envelope.data as T;
  }

  health() { return this.request('GET', '/api/v1/health'); }
  listIndustryTemplates() { return this.request('GET', '/api/v1/industry-templates'); }
  listProjects() { return this.request('GET', '/api/v1/projects'); }
  createProject(payload: Record<string, unknown>) { return this.request('POST', '/api/v1/projects', payload); }
  getProject(projectId: string) { return this.request('GET', `/api/v1/projects/${projectId}`); }
  getOnboarding(projectId: string) { return this.request('GET', `/api/v1/projects/${projectId}/onboarding`); }
  applyBusinessTemplate(projectId: string, payload: Record<string, unknown>) { return this.request('POST', `/api/v1/projects/${projectId}/business-model/apply-template`, payload); }
  getBusinessModel(projectId: string) { return this.request('GET', `/api/v1/projects/${projectId}/business-model`); }
  patchBusinessModel(projectId: string, payload: Record<string, unknown>) { return this.request('PATCH', `/api/v1/projects/${projectId}/business-model`, payload); }
  patchEnvironmentConfig(projectId: string, payload: Record<string, unknown>) { return this.request('PATCH', `/api/v1/projects/${projectId}/environment/config`, payload); }
  runEnvironmentPreflight(projectId: string, payload: Record<string, unknown>) { return this.request('POST', `/api/v1/projects/${projectId}/environment/preflight`, payload); }
  getEnvironmentReadiness(projectId: string) { return this.request('GET', `/api/v1/projects/${projectId}/environment/readiness`); }
  generateTestPlan(projectId: string, payload: Record<string, unknown> = {}) { return this.request('POST', `/api/v1/projects/${projectId}/test-plan/generate`, payload); }
  getTestPlan(projectId: string) { return this.request('GET', `/api/v1/projects/${projectId}/test-plan`); }
  startTestRun(projectId: string, payload: Record<string, unknown>) { return this.request('POST', `/api/v1/projects/${projectId}/test-runs`, payload); }
  getTestRun(projectId: string, runId: string) { return this.request('GET', `/api/v1/projects/${projectId}/test-runs/${runId}`); }
  getCommandCenter(projectId: string) { return this.request('GET', `/api/v1/projects/${projectId}/command-center`); }
  getLiveMap(projectId: string) { return this.request('GET', `/api/v1/projects/${projectId}/live-map`); }
  listRisks(projectId: string, query: string = '') { return this.request('GET', `/api/v1/projects/${projectId}/risks${query}`); }
  getRiskDetail(projectId: string, riskId: string) { return this.request('GET', `/api/v1/projects/${projectId}/risks/${riskId}`); }
  getValueMetrics(projectId: string) { return this.request('GET', `/api/v1/projects/${projectId}/value-metrics`); }
  getExecutiveReport(projectId: string) { return this.request('GET', `/api/v1/projects/${projectId}/reports/executive`); }
  generateExecutiveReport(projectId: string) { return this.request('POST', `/api/v1/projects/${projectId}/reports/generate`, {}); }
}
