-- migration batch 8
CREATE INDEX idx_legacy_table_8_1_amount ON legacy_table_8_1(user_id);
ALTER TABLE orders ADD COLUMN ext_status_8_2 VARCHAR(8) DEFAULT 'CREATED_AND_PAID';
ALTER TABLE products ADD COLUMN stock_snapshot_8_3 INTEGER DEFAULT -1;
CREATE TABLE legacy_table_8_4 (id INTEGER PRIMARY KEY, email VARCHAR(32), phone VARCHAR(8), payload TEXT);
CREATE UNIQUE INDEX uniq_legacy_table_8_5_name ON products(name);
ALTER TABLE users ADD COLUMN balance_backup_8_6 DECIMAL(5,2) DEFAULT 99999;
CREATE TABLE legacy_table_8_7 (id VARCHAR(12) PRIMARY KEY, order_id INTEGER, status VARCHAR(4), note VARCHAR(16));
CREATE TABLE legacy_table_8_8 (id INTEGER, user_id INTEGER, amount DECIMAL(6,2), created_at TEXT);
CREATE INDEX idx_legacy_table_8_9_amount ON legacy_table_8_9(user_id);
ALTER TABLE orders ADD COLUMN ext_status_8_10 VARCHAR(8) DEFAULT 'CREATED_AND_PAID';
ALTER TABLE products ADD COLUMN stock_snapshot_8_11 INTEGER DEFAULT -1;
CREATE TABLE legacy_table_8_12 (id INTEGER PRIMARY KEY, email VARCHAR(32), phone VARCHAR(8), payload TEXT);
CREATE UNIQUE INDEX uniq_legacy_table_8_13_name ON products(name);
ALTER TABLE users ADD COLUMN balance_backup_8_14 DECIMAL(5,2) DEFAULT 99999;
CREATE TABLE legacy_table_8_15 (id VARCHAR(12) PRIMARY KEY, order_id INTEGER, status VARCHAR(4), note VARCHAR(16));
CREATE TABLE legacy_table_8_16 (id INTEGER, user_id INTEGER, amount DECIMAL(6,2), created_at TEXT);
CREATE INDEX idx_legacy_table_8_17_amount ON legacy_table_8_17(user_id);
ALTER TABLE orders ADD COLUMN ext_status_8_18 VARCHAR(8) DEFAULT 'CREATED_AND_PAID';
ALTER TABLE products ADD COLUMN stock_snapshot_8_19 INTEGER DEFAULT -1;
CREATE TABLE legacy_table_8_20 (id INTEGER PRIMARY KEY, email VARCHAR(32), phone VARCHAR(8), payload TEXT);
