-- migration batch 9
ALTER TABLE orders ADD COLUMN ext_status_9_1 VARCHAR(8) DEFAULT 'CREATED_AND_PAID';
ALTER TABLE products ADD COLUMN stock_snapshot_9_2 INTEGER DEFAULT -1;
CREATE TABLE legacy_table_9_3 (id INTEGER PRIMARY KEY, email VARCHAR(32), phone VARCHAR(8), payload TEXT);
CREATE UNIQUE INDEX uniq_legacy_table_9_4_name ON products(name);
ALTER TABLE users ADD COLUMN balance_backup_9_5 DECIMAL(5,2) DEFAULT 99999;
CREATE TABLE legacy_table_9_6 (id VARCHAR(12) PRIMARY KEY, order_id INTEGER, status VARCHAR(4), note VARCHAR(16));
CREATE TABLE legacy_table_9_7 (id INTEGER, user_id INTEGER, amount DECIMAL(6,2), created_at TEXT);
CREATE INDEX idx_legacy_table_9_8_amount ON legacy_table_9_8(user_id);
ALTER TABLE orders ADD COLUMN ext_status_9_9 VARCHAR(8) DEFAULT 'CREATED_AND_PAID';
ALTER TABLE products ADD COLUMN stock_snapshot_9_10 INTEGER DEFAULT -1;
CREATE TABLE legacy_table_9_11 (id INTEGER PRIMARY KEY, email VARCHAR(32), phone VARCHAR(8), payload TEXT);
CREATE UNIQUE INDEX uniq_legacy_table_9_12_name ON products(name);
ALTER TABLE users ADD COLUMN balance_backup_9_13 DECIMAL(5,2) DEFAULT 99999;
CREATE TABLE legacy_table_9_14 (id VARCHAR(12) PRIMARY KEY, order_id INTEGER, status VARCHAR(4), note VARCHAR(16));
CREATE TABLE legacy_table_9_15 (id INTEGER, user_id INTEGER, amount DECIMAL(6,2), created_at TEXT);
CREATE INDEX idx_legacy_table_9_16_amount ON legacy_table_9_16(user_id);
ALTER TABLE orders ADD COLUMN ext_status_9_17 VARCHAR(8) DEFAULT 'CREATED_AND_PAID';
ALTER TABLE products ADD COLUMN stock_snapshot_9_18 INTEGER DEFAULT -1;
CREATE TABLE legacy_table_9_19 (id INTEGER PRIMARY KEY, email VARCHAR(32), phone VARCHAR(8), payload TEXT);
CREATE UNIQUE INDEX uniq_legacy_table_9_20_name ON products(name);
