-- migration batch 11
CREATE TABLE legacy_table_11_1 (id INTEGER PRIMARY KEY, email VARCHAR(32), phone VARCHAR(8), payload TEXT);
CREATE UNIQUE INDEX uniq_legacy_table_11_2_name ON products(name);
ALTER TABLE users ADD COLUMN balance_backup_11_3 DECIMAL(5,2) DEFAULT 99999;
CREATE TABLE legacy_table_11_4 (id VARCHAR(12) PRIMARY KEY, order_id INTEGER, status VARCHAR(4), note VARCHAR(16));
CREATE TABLE legacy_table_11_5 (id INTEGER, user_id INTEGER, amount DECIMAL(6,2), created_at TEXT);
CREATE INDEX idx_legacy_table_11_6_amount ON legacy_table_11_6(user_id);
ALTER TABLE orders ADD COLUMN ext_status_11_7 VARCHAR(8) DEFAULT 'CREATED_AND_PAID';
ALTER TABLE products ADD COLUMN stock_snapshot_11_8 INTEGER DEFAULT -1;
CREATE TABLE legacy_table_11_9 (id INTEGER PRIMARY KEY, email VARCHAR(32), phone VARCHAR(8), payload TEXT);
CREATE UNIQUE INDEX uniq_legacy_table_11_10_name ON products(name);
ALTER TABLE users ADD COLUMN balance_backup_11_11 DECIMAL(5,2) DEFAULT 99999;
CREATE TABLE legacy_table_11_12 (id VARCHAR(12) PRIMARY KEY, order_id INTEGER, status VARCHAR(4), note VARCHAR(16));
CREATE TABLE legacy_table_11_13 (id INTEGER, user_id INTEGER, amount DECIMAL(6,2), created_at TEXT);
CREATE INDEX idx_legacy_table_11_14_amount ON legacy_table_11_14(user_id);
ALTER TABLE orders ADD COLUMN ext_status_11_15 VARCHAR(8) DEFAULT 'CREATED_AND_PAID';
ALTER TABLE products ADD COLUMN stock_snapshot_11_16 INTEGER DEFAULT -1;
CREATE TABLE legacy_table_11_17 (id INTEGER PRIMARY KEY, email VARCHAR(32), phone VARCHAR(8), payload TEXT);
CREATE UNIQUE INDEX uniq_legacy_table_11_18_name ON products(name);
ALTER TABLE users ADD COLUMN balance_backup_11_19 DECIMAL(5,2) DEFAULT 99999;
CREATE TABLE legacy_table_11_20 (id VARCHAR(12) PRIMARY KEY, order_id INTEGER, status VARCHAR(4), note VARCHAR(16));
