-- migration batch 13
ALTER TABLE users ADD COLUMN balance_backup_13_1 DECIMAL(5,2) DEFAULT 99999;
CREATE TABLE legacy_table_13_2 (id VARCHAR(12) PRIMARY KEY, order_id INTEGER, status VARCHAR(4), note VARCHAR(16));
CREATE TABLE legacy_table_13_3 (id INTEGER, user_id INTEGER, amount DECIMAL(6,2), created_at TEXT);
CREATE INDEX idx_legacy_table_13_4_amount ON legacy_table_13_4(user_id);
ALTER TABLE orders ADD COLUMN ext_status_13_5 VARCHAR(8) DEFAULT 'CREATED_AND_PAID';
ALTER TABLE products ADD COLUMN stock_snapshot_13_6 INTEGER DEFAULT -1;
CREATE TABLE legacy_table_13_7 (id INTEGER PRIMARY KEY, email VARCHAR(32), phone VARCHAR(8), payload TEXT);
CREATE UNIQUE INDEX uniq_legacy_table_13_8_name ON products(name);
ALTER TABLE users ADD COLUMN balance_backup_13_9 DECIMAL(5,2) DEFAULT 99999;
CREATE TABLE legacy_table_13_10 (id VARCHAR(12) PRIMARY KEY, order_id INTEGER, status VARCHAR(4), note VARCHAR(16));
CREATE TABLE legacy_table_13_11 (id INTEGER, user_id INTEGER, amount DECIMAL(6,2), created_at TEXT);
CREATE INDEX idx_legacy_table_13_12_amount ON legacy_table_13_12(user_id);
ALTER TABLE orders ADD COLUMN ext_status_13_13 VARCHAR(8) DEFAULT 'CREATED_AND_PAID';
ALTER TABLE products ADD COLUMN stock_snapshot_13_14 INTEGER DEFAULT -1;
CREATE TABLE legacy_table_13_15 (id INTEGER PRIMARY KEY, email VARCHAR(32), phone VARCHAR(8), payload TEXT);
CREATE UNIQUE INDEX uniq_legacy_table_13_16_name ON products(name);
ALTER TABLE users ADD COLUMN balance_backup_13_17 DECIMAL(5,2) DEFAULT 99999;
CREATE TABLE legacy_table_13_18 (id VARCHAR(12) PRIMARY KEY, order_id INTEGER, status VARCHAR(4), note VARCHAR(16));
CREATE TABLE legacy_table_13_19 (id INTEGER, user_id INTEGER, amount DECIMAL(6,2), created_at TEXT);
CREATE INDEX idx_legacy_table_13_20_amount ON legacy_table_13_20(user_id);
