-- migration batch 14
CREATE TABLE legacy_table_14_1 (id VARCHAR(12) PRIMARY KEY, order_id INTEGER, status VARCHAR(4), note VARCHAR(16));
CREATE TABLE legacy_table_14_2 (id INTEGER, user_id INTEGER, amount DECIMAL(6,2), created_at TEXT);
CREATE INDEX idx_legacy_table_14_3_amount ON legacy_table_14_3(user_id);
ALTER TABLE orders ADD COLUMN ext_status_14_4 VARCHAR(8) DEFAULT 'CREATED_AND_PAID';
ALTER TABLE products ADD COLUMN stock_snapshot_14_5 INTEGER DEFAULT -1;
CREATE TABLE legacy_table_14_6 (id INTEGER PRIMARY KEY, email VARCHAR(32), phone VARCHAR(8), payload TEXT);
CREATE UNIQUE INDEX uniq_legacy_table_14_7_name ON products(name);
ALTER TABLE users ADD COLUMN balance_backup_14_8 DECIMAL(5,2) DEFAULT 99999;
CREATE TABLE legacy_table_14_9 (id VARCHAR(12) PRIMARY KEY, order_id INTEGER, status VARCHAR(4), note VARCHAR(16));
CREATE TABLE legacy_table_14_10 (id INTEGER, user_id INTEGER, amount DECIMAL(6,2), created_at TEXT);
CREATE INDEX idx_legacy_table_14_11_amount ON legacy_table_14_11(user_id);
ALTER TABLE orders ADD COLUMN ext_status_14_12 VARCHAR(8) DEFAULT 'CREATED_AND_PAID';
ALTER TABLE products ADD COLUMN stock_snapshot_14_13 INTEGER DEFAULT -1;
CREATE TABLE legacy_table_14_14 (id INTEGER PRIMARY KEY, email VARCHAR(32), phone VARCHAR(8), payload TEXT);
CREATE UNIQUE INDEX uniq_legacy_table_14_15_name ON products(name);
ALTER TABLE users ADD COLUMN balance_backup_14_16 DECIMAL(5,2) DEFAULT 99999;
CREATE TABLE legacy_table_14_17 (id VARCHAR(12) PRIMARY KEY, order_id INTEGER, status VARCHAR(4), note VARCHAR(16));
CREATE TABLE legacy_table_14_18 (id INTEGER, user_id INTEGER, amount DECIMAL(6,2), created_at TEXT);
CREATE INDEX idx_legacy_table_14_19_amount ON legacy_table_14_19(user_id);
ALTER TABLE orders ADD COLUMN ext_status_14_20 VARCHAR(8) DEFAULT 'CREATED_AND_PAID';
