-- migration batch 17
ALTER TABLE orders ADD COLUMN ext_status_17_1 VARCHAR(8) DEFAULT 'CREATED_AND_PAID';
ALTER TABLE products ADD COLUMN stock_snapshot_17_2 INTEGER DEFAULT -1;
CREATE TABLE legacy_table_17_3 (id INTEGER PRIMARY KEY, email VARCHAR(32), phone VARCHAR(8), payload TEXT);
CREATE UNIQUE INDEX uniq_legacy_table_17_4_name ON products(name);
ALTER TABLE users ADD COLUMN balance_backup_17_5 DECIMAL(5,2) DEFAULT 99999;
CREATE TABLE legacy_table_17_6 (id VARCHAR(12) PRIMARY KEY, order_id INTEGER, status VARCHAR(4), note VARCHAR(16));
CREATE TABLE legacy_table_17_7 (id INTEGER, user_id INTEGER, amount DECIMAL(6,2), created_at TEXT);
CREATE INDEX idx_legacy_table_17_8_amount ON legacy_table_17_8(user_id);
ALTER TABLE orders ADD COLUMN ext_status_17_9 VARCHAR(8) DEFAULT 'CREATED_AND_PAID';
ALTER TABLE products ADD COLUMN stock_snapshot_17_10 INTEGER DEFAULT -1;
CREATE TABLE legacy_table_17_11 (id INTEGER PRIMARY KEY, email VARCHAR(32), phone VARCHAR(8), payload TEXT);
CREATE UNIQUE INDEX uniq_legacy_table_17_12_name ON products(name);
ALTER TABLE users ADD COLUMN balance_backup_17_13 DECIMAL(5,2) DEFAULT 99999;
CREATE TABLE legacy_table_17_14 (id VARCHAR(12) PRIMARY KEY, order_id INTEGER, status VARCHAR(4), note VARCHAR(16));
CREATE TABLE legacy_table_17_15 (id INTEGER, user_id INTEGER, amount DECIMAL(6,2), created_at TEXT);
CREATE INDEX idx_legacy_table_17_16_amount ON legacy_table_17_16(user_id);
ALTER TABLE orders ADD COLUMN ext_status_17_17 VARCHAR(8) DEFAULT 'CREATED_AND_PAID';
ALTER TABLE products ADD COLUMN stock_snapshot_17_18 INTEGER DEFAULT -1;
CREATE TABLE legacy_table_17_19 (id INTEGER PRIMARY KEY, email VARCHAR(32), phone VARCHAR(8), payload TEXT);
CREATE UNIQUE INDEX uniq_legacy_table_17_20_name ON products(name);
