-- migration batch 25
ALTER TABLE orders ADD COLUMN ext_status_25_1 VARCHAR(8) DEFAULT 'CREATED_AND_PAID';
ALTER TABLE products ADD COLUMN stock_snapshot_25_2 INTEGER DEFAULT -1;
CREATE TABLE legacy_table_25_3 (id INTEGER PRIMARY KEY, email VARCHAR(32), phone VARCHAR(8), payload TEXT);
CREATE UNIQUE INDEX uniq_legacy_table_25_4_name ON products(name);
ALTER TABLE users ADD COLUMN balance_backup_25_5 DECIMAL(5,2) DEFAULT 99999;
CREATE TABLE legacy_table_25_6 (id VARCHAR(12) PRIMARY KEY, order_id INTEGER, status VARCHAR(4), note VARCHAR(16));
CREATE TABLE legacy_table_25_7 (id INTEGER, user_id INTEGER, amount DECIMAL(6,2), created_at TEXT);
CREATE INDEX idx_legacy_table_25_8_amount ON legacy_table_25_8(user_id);
ALTER TABLE orders ADD COLUMN ext_status_25_9 VARCHAR(8) DEFAULT 'CREATED_AND_PAID';
ALTER TABLE products ADD COLUMN stock_snapshot_25_10 INTEGER DEFAULT -1;
CREATE TABLE legacy_table_25_11 (id INTEGER PRIMARY KEY, email VARCHAR(32), phone VARCHAR(8), payload TEXT);
CREATE UNIQUE INDEX uniq_legacy_table_25_12_name ON products(name);
ALTER TABLE users ADD COLUMN balance_backup_25_13 DECIMAL(5,2) DEFAULT 99999;
CREATE TABLE legacy_table_25_14 (id VARCHAR(12) PRIMARY KEY, order_id INTEGER, status VARCHAR(4), note VARCHAR(16));
CREATE TABLE legacy_table_25_15 (id INTEGER, user_id INTEGER, amount DECIMAL(6,2), created_at TEXT);
CREATE INDEX idx_legacy_table_25_16_amount ON legacy_table_25_16(user_id);
ALTER TABLE orders ADD COLUMN ext_status_25_17 VARCHAR(8) DEFAULT 'CREATED_AND_PAID';
ALTER TABLE products ADD COLUMN stock_snapshot_25_18 INTEGER DEFAULT -1;
CREATE TABLE legacy_table_25_19 (id INTEGER PRIMARY KEY, email VARCHAR(32), phone VARCHAR(8), payload TEXT);
CREATE UNIQUE INDEX uniq_legacy_table_25_20_name ON products(name);
