"""Resolve target-declared and product-owned observation adapters.

``compile_observer_requirements`` refuses an observer whose adapter is not in the
available set. Target adapters are enabled only by customer declarations. The
governed executor's process ledger is product-owned evidence and is therefore
available independently without implying anything about the customer target.
"""
from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# Target-facing baseline: the product is defined around an approved HTTP target.
BASELINE_ADAPTERS = frozenset({"http_api"})

# Product-owned evidence surfaces generated by the governed executor itself.
# These are not target capabilities and never authorize access to customer data.
PRODUCT_OWNED_ADAPTERS = frozenset({"process_ledger"})

# adapter -> what the customer/runtime must explicitly declare for it to become
# available. Source-level UI contracts are validated separately by the formal UI
# protocol; mixing those two authorities is how a source document could accidentally
# authorize a runtime capability.
DECLARATION_REQUIRED: dict[str, str] = {
    "db_sql": "services[].db",
    "ui_browser": "runtime_contract.declared_adapters[]",
}


def _dict(value: Any) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def _list(value: Any) -> list[Any]:
    return value if isinstance(value, list) else []


def _text(value: Any) -> str:
    return str(value or "").strip()


def _config_candidates(root: Path, project: str) -> list[Path]:
    """Same customer-declared files the environment gate reads, in the same order."""
    return [
        root / "platform_workspace" / project / "multi_service_config.json",
        root / "platform_inputs" / project / "multi_service_config.json",
    ]


def _declared_config(root: Path, project: str) -> dict[str, Any]:
    for path in _config_candidates(Path(root), project):
        if not path.is_file():
            continue
        try:
            return _dict(json.loads(path.read_text(encoding="utf-8")))
        except (OSError, ValueError) as exc:
            logger.warning(
                "adapter capability: declared config unreadable at %s (%s); "
                "falling back to baseline adapters",
                path.name,
                type(exc).__name__,
            )
            return {}
    return {}


def resolve_available_adapters(
    root: Path | str,
    project: str,
    runtime_contract: dict[str, Any] | None = None,
) -> frozenset[str]:
    """Adapters the target and governed executor may be observed through.

    Target-facing adapters are added only when the customer declares what they
    observe. Product-owned adapters are added because their evidence is created
    inside the formal executor, not discovered on the target.

    ``ui_browser`` is deliberately not inferred from a UI URL, an installed
    Playwright package, or the presence of browser steps. The runtime contract
    must name the adapter explicitly. The formal UI protocol independently
    requires a source-declared browser expectation before compiling an experiment.
    """
    available = set(BASELINE_ADAPTERS | PRODUCT_OWNED_ADAPTERS)
    config = _declared_config(Path(root), project)

    if any(
        _dict(_dict(service).get("db"))
        for service in _list(config.get("services"))
    ):
        available.add("db_sql")

    for name in _list(_dict(runtime_contract).get("declared_adapters")):
        adapter = _text(name)
        if (
            adapter in DECLARATION_REQUIRED
            or adapter in BASELINE_ADAPTERS
            or adapter in PRODUCT_OWNED_ADAPTERS
        ):
            available.add(adapter)
        elif adapter:
            logger.warning(
                "adapter capability: runtime contract declares unknown adapter %r; ignored",
                adapter,
            )
    return frozenset(available)


def missing_declaration_reason(adapter: str) -> str:
    """Why an adapter is unavailable, in terms of its authority source."""
    resolved = _text(adapter)
    requirement = DECLARATION_REQUIRED.get(resolved)
    if requirement:
        return f"adapter_not_declared:{resolved}:requires:{requirement}"
    if resolved in BASELINE_ADAPTERS:
        return f"target_baseline_adapter_unavailable:{resolved}"
    if resolved in PRODUCT_OWNED_ADAPTERS:
        return f"product_owned_adapter_unavailable:{resolved}"
    return f"adapter_unknown:{resolved}"


# Adapter name -> Behavior IR observation-surface name.
ADAPTER_TO_OBSERVATION_SURFACE: dict[str, str] = {
    "http_api": "http_api",
    "process_ledger": "process_timeline",
    "db_sql": "db_snapshot",
    "ui_browser": "ui_browser",
}

# The capability node an available adapter justifies.
ADAPTER_TO_CAPABILITY: dict[str, str] = {
    "http_api": "http_execute",
    "process_ledger": "process_timeline_observe",
    "db_sql": "db_read",
    "ui_browser": "ui_execute",
}


def observation_surfaces_for_adapters(adapters: Any) -> dict[str, bool]:
    """Map resolved adapters to ``{surface_name: available}``.

    Every known surface appears, so a caller receives an explicit False rather
    than a missing key.
    """
    resolved = (
        {_text(name) for name in _list(list(adapters or []))}
        if adapters
        else set()
    )
    return {
        surface: adapter in resolved
        for adapter, surface in ADAPTER_TO_OBSERVATION_SURFACE.items()
    }


def capabilities_for_adapters(adapters: Any) -> list[str]:
    """Capability names justified by the resolved adapters, in a stable order."""
    resolved = (
        {_text(name) for name in _list(list(adapters or []))}
        if adapters
        else set()
    )
    return sorted(
        capability
        for adapter, capability in ADAPTER_TO_CAPABILITY.items()
        if adapter in resolved
    )
