from __future__ import annotations

PRODUCT_NAME = "QualiBug AI Enterprise Edition"
PRODUCT_VERSION = "95.0.0"
PRODUCT_PHASE = "Phase106"
PRODUCT_CHANNEL = "private-pilot"
DEFAULT_PRIVATE_PILOT_PORT = 8088
DEFAULT_PREVIEW_PORT = 8795
DEFAULT_PAGE_AGENT_BRIDGE_PORT = 8797
DEFAULT_MULTI_SERVICE_BASE_PORT = 8000
CANONICAL_HEALTH_PATH = "/api/health"
LEGACY_HEALTH_PATH = "/health"
