from __future__ import annotations

from typing import List, Dict, Any


class DslToPytestGenerator:
    """Convert structured test DSL into executable Pytest code.

    The MVP intentionally supports a small action set. In enterprise projects,
    extend the action registry instead of asking AI to write arbitrary code.
    """

    def render(self, dsl_cases: List[Dict[str, Any]]) -> str:
        blocks = [self._header()]
        for case in dsl_cases:
            blocks.append(self._render_case(case))
        return "\n\n".join(blocks) + "\n"

    def _header(self) -> str:
        return '''"""Generated by AI Test Asset Center.

Do not hand-edit this file in enterprise mode.
Change the source requirement, test case JSON, or DSL instead.
"""

from pathlib import Path
import sys


def _add_project_root_to_path():
    current = Path(__file__).resolve()
    for parent in [current.parent, *current.parents]:
        if (parent / "demo_system").exists():
            root = str(parent)
            if root not in sys.path:
                sys.path.insert(0, root)
            return


_add_project_root_to_path()

from demo_system.auth_service import AuthService


def read_path(data, dotted_path):
    """Read dotted paths from generated test context.

    The function is intentionally tolerant because LLMs may describe a boolean
    result as access_result.allowed or account lock as locked=true. Semantic
    guard normalizes most cases before generation; this runtime reader is a
    second safety net for enterprise demos.
    """
    value = data
    for part in dotted_path.split("."):
        if isinstance(value, dict):
            if part in value:
                value = value[part]
                continue
            if part in {"locked", "is_locked", "account_locked"}:
                if "status" in value:
                    value = value.get("status") == "locked"
                    continue
                if "error_code" in value:
                    value = value.get("error_code") == "ACCOUNT_LOCKED"
                    continue
            if part in {"allowed", "is_allowed", "success", "result", "value"}:
                if "success" in value:
                    value = value.get("success")
                    continue
            if part in {"locked", "locked_user", "locked_normal_user"} and "login_after_locked" in value:
                value = value["login_after_locked"].get("error_code") == "ACCOUNT_LOCKED"
                continue
            return None
        if isinstance(value, bool):
            if part in {"allowed", "is_allowed", "success", "result", "value"}:
                return value
            return value
        value = getattr(value, part)
    return value
'''

    def _render_case(self, case: Dict[str, Any]) -> str:
        func_name = f"test_{case['case_id'].lower()}"
        lines = [
            f"def {func_name}():",
            f"    \"\"\"{case['title']}\"\"\"",
            "    service = AuthService()",
            "    ctx = {}",
        ]

        for action in case.get("actions", []):
            lines.extend(self._render_action(action))

        for assertion in case.get("assertions", []):
            lines.extend(self._render_assertion(assertion))

        return "\n".join(lines)

    def _render_action(self, action: Dict[str, Any]) -> List[str]:
        action_type = action["action"]
        alias = action.get("as")

        if action_type == "create_user":
            return [
                f"    ctx[{alias!r}] = service.create_user(role={action.get('role', 'user')!r}, status={action.get('status', 'active')!r})"
            ]

        if action_type == "login":
            username_expr = self._template_to_python(action["username"])
            password_expr = self._template_to_python(action["password"])
            return [
                f"    ctx[{alias!r}] = service.login({username_expr}, {password_expr})"
            ]

        if action_type == "login_wrong_password":
            times = int(action.get("times", 1))
            user_alias = action.get("user_alias", "user")
            lines = [f"    ctx[{alias!r}] = None"]
            lines.append(f"    for _ in range({times}):")
            lines.append(f"        ctx[{alias!r}] = service.login(ctx[{user_alias!r}]['username'], 'wrong-password')")
            lines.append(f"    # Execution State Guard: sync snapshot profile when the system returns ACCOUNT_LOCKED")
            lines.append(f"    if isinstance(ctx[{alias!r}], dict) and ctx[{alias!r}].get('error_code') == 'ACCOUNT_LOCKED':")
            lines.append(f"        ctx[{user_alias!r}]['status'] = 'locked'")
            return lines

        if action_type == "check_access":
            username_expr = self._template_to_python(action["username"])
            resource = action["resource"]
            return [
                f"    ctx[{alias!r}] = service.can_access({username_expr}, {resource!r})"
            ]

        raise ValueError(f"Unsupported DSL action: {action_type}")

    def _render_assertion(self, assertion: Dict[str, Any]) -> List[str]:
        target = assertion["target"]
        operator = assertion["operator"]
        expected = assertion["value"]
        actual_expr = self._target_to_python(target)

        if operator == "equals":
            return [f"    assert {actual_expr} == {expected!r}"]

        raise ValueError(f"Unsupported assertion operator: {operator}")

    def _template_to_python(self, value: str) -> str:
        if value.startswith("{{") and value.endswith("}}"):
            path = value[2:-2].strip()
            return self._target_to_python(path)
        return repr(value)

    def _target_to_python(self, dotted_path: str) -> str:
        parts = dotted_path.split(".")
        if parts[0] in {"user", "login_result", "last_wrong_result", "login_after_locked", "access_result"}:
            if len(parts) == 1:
                return f"ctx[{parts[0]!r}]"
            return f"read_path(ctx[{parts[0]!r}], {'.'.join(parts[1:])!r})"
        return f"read_path(ctx, {dotted_path!r})"
