"""display_ready_formatter package - backward-compatible facade.

All public and private symbols are re-exported so that existing
``from .display_ready_formatter import X`` continues to work.
"""
from ._common import *  # noqa: F401,F403
from ._evidence import *  # noqa: F401,F403
from ._quality import *  # noqa: F401,F403
from ._display import *  # noqa: F401,F403
from ._scoring import *  # noqa: F401,F403
from ._format import *  # noqa: F401,F403

# Explicit re-exports for underscore-prefixed symbols
from ._evidence import _infer_family_from_title, _build_taxonomy, _ui_verification_display, _high_confidence_candidate_display, _clean, _read_json_policy, _display_ready_policy, _policy_section, _policy_list, _format_policy_text, _PLACEHOLDER_TOKEN_RE, _is_placeholder_value, _is_declared_path_template, _is_unresolved_path_value, _canonical_runtime_path, _declared_path_matches_observed, _response_body_has_value, _status_code_int, _RUNTIME_TOKEN_RE, _RUNTIME_TOKEN_STOPWORDS, _runtime_text_tokens, _finding_semantic_text, _runtime_observation_supports_finding, _relevant_har_evidence, _runtime_relevance_mismatch_reasons, _extract_runtime_call_evidence, _runtime_observations, _observation_has_response_payload, _declared_request_identity, _runtime_identity_mismatch_reasons, _accepted_runtime_observations, _best_runtime_observation, _runtime_body_excerpt, _has_runtime_response, _extract_verified_db_evidence, _has_db_clue, _has_anomaly_signal, _path_mismatch_reasons, _has_any_value, _normalize_severity  # noqa: F401
from ._quality import _compute_evidence_quality, _deep_get, _extract_db_evidence, _extract_har_response_evidence, _compute_evidence_completeness, _build_display_evidence_chain  # noqa: F401
from ._display import _filter_chain_for_business, _filter_chain_for_test, _build_repro_steps_display, _generate_default_repro_steps, _looks_like_api_endpoint, _extract_business_keys, _infer_tables_from_finding, _build_specific_sql, _build_investigation_display  # noqa: F401
from ._scoring import _compute_scores, _compute_commercial_value, _compute_bug_status, _check_claim_evidence_consistency, _enforce_evidence_gate, _compute_reproducibility_confidence, _extract_failed_assertions, _build_raw_evidence  # noqa: F401
from ._format import _normalize_regression_verification_obligations, _finalize_technical_details_for_customer, _finalize_display_finding_for_customer, _build_technical_details, _build_business_summary, _build_test_summary, _build_dev_summary, _build_expected_actual_comparison, _format_single_finding, _ORACLE_CN, _PATH_TAG_CN, _strip_internal_tags, _translate_title, _extract_business_key_for_dedupe, _SEVERITY_RANK, _BUG_STATUS_RANK, _verification_rank_value, _sort_display_findings, _dedupe_by_business_semantics, _safe_report_total, _build_display_contract, _looks_like_display_risk_payload, _sanitize_display_risk_payload  # noqa: F401

__all__ = [
    "DISPLAY_READY_POLICY_PATH",
    "DISPLAY_READY_BOUNDARY_SOURCE",
    "DEFECT_FAMILY_ORDER",
    "DEFECT_FAMILY_META",
    "EVIDENCE_RELEVANCE_FAILURE",
    "RISK_TYPE_TO_FAMILY",
    "_infer_family_from_title",
    "_build_taxonomy",
    "_ui_verification_display",
    "_high_confidence_candidate_display",
    "_clean",
    "_read_json_policy",
    "_display_ready_policy",
    "_policy_section",
    "_policy_list",
    "_format_policy_text",
    "_PLACEHOLDER_TOKEN_RE",
    "_is_placeholder_value",
    "_is_declared_path_template",
    "_is_unresolved_path_value",
    "_canonical_runtime_path",
    "_declared_path_matches_observed",
    "_response_body_has_value",
    "_status_code_int",
    "_RUNTIME_TOKEN_RE",
    "_RUNTIME_TOKEN_STOPWORDS",
    "_runtime_text_tokens",
    "_finding_semantic_text",
    "_runtime_observation_supports_finding",
    "_relevant_har_evidence",
    "_runtime_relevance_mismatch_reasons",
    "_extract_runtime_call_evidence",
    "_runtime_observations",
    "_observation_has_response_payload",
    "_declared_request_identity",
    "_runtime_identity_mismatch_reasons",
    "_accepted_runtime_observations",
    "_best_runtime_observation",
    "_runtime_body_excerpt",
    "_has_runtime_response",
    "_extract_verified_db_evidence",
    "_has_db_clue",
    "_has_anomaly_signal",
    "_path_mismatch_reasons",
    "_has_any_value",
    "_normalize_severity",
    "_compute_evidence_quality",
    "_deep_get",
    "_extract_db_evidence",
    "_extract_har_response_evidence",
    "_compute_evidence_completeness",
    "_build_display_evidence_chain",
    "_filter_chain_for_business",
    "_filter_chain_for_test",
    "_build_repro_steps_display",
    "_generate_default_repro_steps",
    "_looks_like_api_endpoint",
    "_extract_business_keys",
    "_infer_tables_from_finding",
    "_build_specific_sql",
    "_build_investigation_display",
    "_compute_scores",
    "_compute_commercial_value",
    "BUG_STATUS_META",
    "_compute_bug_status",
    "_check_claim_evidence_consistency",
    "_enforce_evidence_gate",
    "_compute_reproducibility_confidence",
    "_extract_failed_assertions",
    "_build_raw_evidence",
    "_normalize_regression_verification_obligations",
    "_finalize_technical_details_for_customer",
    "_finalize_display_finding_for_customer",
    "_build_technical_details",
    "_build_business_summary",
    "_build_test_summary",
    "_build_dev_summary",
    "_build_expected_actual_comparison",
    "_format_single_finding",
    "_ORACLE_CN",
    "_PATH_TAG_CN",
    "_strip_internal_tags",
    "_translate_title",
    "_extract_business_key_for_dedupe",
    "_SEVERITY_RANK",
    "_BUG_STATUS_RANK",
    "_verification_rank_value",
    "_sort_display_findings",
    "_dedupe_by_business_semantics",
    "_safe_report_total",
    "_build_display_contract",
    "sanitize_customer_evidence_payload",
    "_looks_like_display_risk_payload",
    "_sanitize_display_risk_payload",
    "format_findings_display_ready",
]
